name: GraalVM Native Image build
on: [push, pull_request]
jobs:
  build-windows:

    runs-on: [ windows-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: foojayio/setup-java@disco
        with:
          java-version: 17.0.2
          architecture: x64
      - name: Build with Gradle
        run: .\gradlew.bat assemble

      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '17'
          components: 'native-image'

      - name: Build native-image on Windows
        run: native-image.cmd -cp classes;discocli-17.0.2.jar --no-server -H:Name=discocli eu.hansolo.discocli.DiscoCLI --no-fallback --static --enable-http --enable-https

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: discocli
          path: discocli*
          